version: "3.9"

services:
  db:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: rootpass
      TZ: ${TZ}
    ports:
      - "3307:3306" 
    volumes:
      - dbdata:/var/lib/mysql
      - ./sql/init:/docker-entrypoint-initdb.d:ro

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      TZ: ${TZ}
    volumes:
      - ./public:/var/www/public
      - ./src:/var/www/src
    depends_on:
      - db

  nginx:
    image: nginx:1.27-alpine
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ./public:/var/www/public:ro
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  adminer:
    image: adminer:4
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  dbdata: